version: '3'

services:
  planner:
    build:
      context: ./planner
      dockerfile: Dockerfile.planner
    volumes:
      - ./planner:/app/planner  # Montage du code du planner
    depends_on:
      - worker  # Dépend du service worker
    networks:
      - app-network

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.worker
    volumes:
      - ./worker:/app/worker  # Montage du code du worker
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
