version: '3'

services:
  planner:
    build:
      context: ./planner
      dockerfile: Dockerfile.planner
    volumes:
      - ./planner:/app/planner  # Montage du code du planner
    depends_on:
      - worker  # Dépend du service worker
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      SPECIALIZATION: add

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.worker
    volumes:
      - ./worker:/app/worker  # Montage du code du worker
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      SPECIALIZATION: add

networks:
  app-network:
    driver: bridge
