FROM node:18.18.2
# Create app directory
WORKDIR /app
COPY package.json ./package.json
COPY package-lock.json ./package-lock.json
RUN npm install
COPY . .
EXPOSE 3000
ENV TASKS=20
CMD ["node", "planner_code.js"]
