FROM node:14

WORKDIR /worker

# Copy package.json and package-lock.json
COPY package*.json ./

ENV SPECIALIZATION=add

# Install dependencies
RUN npm install

COPY worker_code.js .

CMD ["node", "worker_code.js"]
